### ISSUE TITLE
Support for Calibre-generated metadata & cover in OPDS catalog app

### ISSUE THREAD

**Issue by gpaumier** [Yetangitu/owncloud-apps#4]
(Splitting from the unrelated #3 )

> My use case is the following: I have a Calibre library with tons of metadata & covers, and I'd like to use the OPDS catalog app to make it available to my devices, but I don't know if the OPDS app looks at the existing `metadata.opf` and `cover.jpg` files already provided by Calibre. I would like to avoid duplication.

**Comment by gpaumier** [comment]
Err… Apparently messages can't be delivered to the e-mail address listed on your GitHub profile.

**Comment by Yetangitu** [comment]
Strange, as I get mail on that address all the time. Try again?

**Comment by Yetangitu** [comment]
I committed an initial version (0.5.9) which supports both calibre metadata as well as covers. Give it a try on a more extensive Calibre library and let me know if it works...

**Comment by gpaumier** [comment]
Awesome! I've cloned and installed it, but I get the same error described later in #3 (empty database & catalog). I'll set up a vanilla test instance of ownCloud tomorrow to investigate that other issue since it's blocking this. I'll report back after that.

Thanks agin!

**Comment by Yetangitu** [comment]
Try this patch:

```
diff --git a/files_opds/lib/meta.php b/files_opds/lib/meta.php
index e28f176..58c6774 100644
--- a/files_opds/lib/meta.php
+++ b/files_opds/lib/meta.php
@@ -30,7 +30,7 @@ class Meta
                 * scanned once, even if they don't contain valid metadate.
                 */
                $meta['id'] = $id;
-               $meta['updated'] = date("Y-m-d\TH:i:sP");
+               $meta['updated'] = date("Y-m-d H:i:s");
                $meta['date'] = '';
                $meta['author'] = '';
                $meta['title'] = '';
```

**Comment by Yetangitu** [comment]
The patch is now committed to the repo as it does not seem to cause harm and has the potential to solve your problem. The question remains why it works for me, but not for you.

**Comment by gpaumier** [comment]
Thank you. I applied the patch earlier today but it didn't fix the issue. I still haven't tried on a new install but I couldn't do that today. I'll try to do it tomorrow, and if not then I'll do it for sure this week-end and report back. I appreciate all your help!

**Comment by Yetangitu** [comment]
FYI, I released 0.6.0 (including Calibre-support) on apps.owncloud.com. I tested it with a Calibre library containing app. 4000 publications, it seems to work.

**Comment by Yetangitu** [comment]
0.6.1 released, adds option to schedule rescan of metadata. This is needed to get rid of pre-Calibre metadata for those who use Calibre.
